# wrangler.toml
name = "truevo-registry"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".next/standalone"

[vars]
NODE_VERSION = "18"

[[build]]
command = "npm run build"

[[build.upload]]
directory = ".next/standalone"